/********************************** (C) COPYRIGHT *******************************
 * File Name          : main_v3f.c
 * Author             : WCH
 * Version            : V1.0.4
 * Date               : 2026/03/27
 * Description        : Main program body for V3F.
 *********************************************************************************
 * Copyright (c) 2025 Nanjing Qinheng Microelectronics Co., Ltd.
 * Attention: This software (modified or not) and binary are used for
 * microcontroller manufactured by Nanjing Qinheng Microelectronics.
 *******************************************************************************/
/*
 *@Note
 * The current in the chip¡¯s VDD12 power domain is relatively high.
 * To reduce the chip¡¯s power consumption and minimize heat generated by the internal LDO, 
 * the LDO output voltage can be lowered and this power supply can be provided externally 
 * (It can be generated by an external DC-DC converter CH2003).
 * This example demonstrates how to reduce the sleep current in STOP mode 
 * (where the voltage regulator is in low-power mode) when the VDD12 power is supplied externally.
 *
 * Vout£¨VDD12)
 *   |
 *   R1
 *   |
 *   +------ R3 ------ GPIO(0/3V3)
 *   |
 *   R2
 *   |
 *  GND
 * The power supply circuit using the CH2003 chip can be referred to the data manual. Some of the circuits are shown above.
 * For chips for which the 5th digit from the end of the batch number is less than or equal to 2, it is recommended that:
 * R1=200K£¬R2=200K£¬R3=4700K£¬GPIO@0 Vout = 1.225V, @GPIO@3V3 Vout = 1.085V
 * For chips with the 5th digit from the end of the batch number greater than 2, it is recommended that:
 * R1=200K£¬R2=220K£¬R3=2000K£¬GPIO@0 Vout = 1.205V, @GPIO@3V3 Vout = 0.875V
 *
 */
#include "debug.h"
#include "hardware.h"

void GPIO_Config(void)
{
	GPIO_InitTypeDef GPIO_InitStructure = {0};
	RCC_HB2PeriphClockCmd(RCC_HB2Periph_AFIO | RCC_HB2Periph_GPIOA | RCC_HB2Periph_GPIOB | RCC_HB2Periph_GPIOC |
						  RCC_HB2Periph_GPIOD| RCC_HB2Periph_GPIOE | RCC_HB2Periph_GPIOF, ENABLE);

	/* To reduce power consumption, unused I/O is configured in pull-down input mode. */
	GPIO_PinRemapConfig(GPIO_Remap_SWJ_Disable, ENABLE);
	GPIO_InitStructure.GPIO_Pin = GPIO_Pin_All;
	GPIO_InitStructure.GPIO_Mode = GPIO_Mode_IPD;
	GPIO_Init(GPIOA, &GPIO_InitStructure);
	GPIO_Init(GPIOB, &GPIO_InitStructure);
	GPIO_Init(GPIOC, &GPIO_InitStructure);
	GPIO_Init(GPIOD, &GPIO_InitStructure);
	GPIO_Init(GPIOE, &GPIO_InitStructure);
	GPIO_Init(GPIOF, &GPIO_InitStructure);

	/* PE3 is used to adjust the DC-DC output voltage of CH2003K. 
	GPIO low level (0) corresponds to the normal operation mode; 
	GPIO high level (3V3) corresponds to the stop mode (the regulator enters low-power mode). */
	GPIO_InitStructure.GPIO_Pin = GPIO_Pin_3;
	GPIO_InitStructure.GPIO_Mode = GPIO_Mode_Out_PP;
	GPIO_InitStructure.GPIO_Speed = GPIO_Speed_Very_High;
	GPIO_Init(GPIOE, &GPIO_InitStructure);
}

/*********************************************************************
 * @fn      main
 *
 * @brief   Main program.
 *
 * @return  none
 */
int main(void)
{	
	SystemInit();
	SystemAndCoreClockUpdate();
	Delay_Init();
	GPIO_Config();
	/* GPIO low level (0) corresponds to the normal operation mode */
	GPIO_ResetBits(GPIOE, GPIO_Pin_3);

	/* The current in the chip¡¯s VDD12 power domain is relatively high.
	To reduce the chip¡¯s power consumption and minimize heat generated by the internal LDO, 
	the LDO output voltage can be lowered and this power supply can be provided externally 
	(which can be generated by an external DC-DC converter).
    Note that this operation should be performed after the external 1.2V supply has stabilized, 
	and the external 1.2V power supply must have a capacity sufficiently greater than the current 
	consumption reference value for VDD12 specified in the DS datasheet. */
	PWR_VDD12ExternPower();

	USART_Printf_Init(115200);
	printf("SystemClk:%d\r\n", SystemClock);
	printf("V3F SystemCoreClk:%d\r\n", SystemCoreClock);
	Delay_Ms(500);

	/* For chips with externally sealed VIO18 pins, if users use 3.3V and do not require low voltage support, 
	VDDIO and VIO18 can be short circuited off chip. By configuring VSEL_VIO18 in the software to turn off LDO,
	power consumption can be reduced. For chips that do not include the VIO18 pin, VDDIO and VIO18 are short 
	circuited on the chip. After power on, LDO needs to be turned off in the software through VSEL_VIO18 to 
	reduce power consumption. */
	RCC_HB1PeriphClockCmd(RCC_HB1Periph_PWR,ENABLE);
	PWR_VIO18ModeCfg(PWR_VIO18CFGMODE_SW);
	PWR_VIO18LevelCfg(PWR_VIO18Level_MODE5);

#if (Run_Core == Run_Core_V3FandV5F)
	NVIC_WakeUp_V5F(Core_V5F_StartAddr);/* wake up v5f */
	HSEM_ITConfig(HSEM_ID0, ENABLE);
    NVIC->SCTLR |= 1<<4;
	RCC_HB1PeriphClockCmd(RCC_HB1Periph_PWR,ENABLE);
	PWR_EnterSTOPMode(PWR_Regulator_ON, PWR_STOPEntry_WFE);
	HSEM_ClearFlag(HSEM_ID0);
    Hardware();

#elif (Run_Core == Run_Core_V3F)
    Hardware();

#elif (Run_Core == Run_Core_V5F)
	NVIC_WakeUp_V5F(Core_V5F_StartAddr);/* wake up v5f */
	RCC_HB1PeriphClockCmd(RCC_HB1Periph_PWR,ENABLE);
	PWR_EnterSTOPMode(PWR_Regulator_ON, PWR_STOPEntry_WFI);
#endif
    while(1)
	{
		printf("V3F running...\r\n");
		Delay_Ms(1000);
	}
}
