/********************************** (C) COPYRIGHT *******************************
 * File Name          : main.c
 * Author             : WCH
 * Version            : V1.0.4
 * Date               : 2026/03/27
 * Description        : Main program body.
 *********************************************************************************
 * Copyright (c) 2025 Nanjing Qinheng Microelectronics Co., Ltd.
 * Attention: This software (modified or not) and binary are used for
 * microcontroller manufactured by Nanjing Qinheng Microelectronics.
 *******************************************************************************/
/*
 *@Note
 * The current in the chip¡¯s VDD12 power domain is relatively high.
 * To reduce the chip¡¯s power consumption and minimize heat generated by the internal LDO, 
 * the LDO output voltage can be lowered and this power supply can be provided externally 
 * (It can be generated by an external DC-DC converter CH2003).
 * This example demonstrates how to reduce the sleep current in STOP mode 
 * (where the voltage regulator is in low-power mode) when the VDD12 power is supplied externally.
 *
 * Vout£¨VDD12)
 *   |
 *   R1
 *   |
 *   +------ R3 ------ GPIO(0/3V3)
 *   |
 *   R2
 *   |
 *  GND
 * The power supply circuit using the CH2003 chip can be referred to the data manual. Some of the circuits are shown above.
 * For chips for which the 5th digit from the end of the batch number is less than or equal to 2, it is recommended that:
 * R1=200K£¬R2=200K£¬R3=4700K£¬GPIO@0 Vout = 1.225V, @GPIO@3V3 Vout = 1.085V
 * For chips with the 5th digit from the end of the batch number greater than 2, it is recommended that:
 * R1=200K£¬R2=220K£¬R3=2000K£¬GPIO@0 Vout = 1.205V, @GPIO@3V3 Vout = 0.875V
 *
 */
#include "debug.h"
#include "hardware.h"

/*********************************************************************
 * @fn      main
 *
 * @brief   Main program.
 *
 * @return  none
 */
int main(void)
{
	SystemAndCoreClockUpdate();
	Delay_Init();
	USART_Printf_Init(115200);
	printf("V5F SystemCoreClk:%d\r\n", SystemCoreClock);
	Delay_Ms(500);
#if (Run_Core == Run_Core_V3FandV5F)
	HSEM_FastTake(HSEM_ID0);
	HSEM_ReleaseOneSem(HSEM_ID0, 0);
	Hardware();

#elif (Run_Core == Run_Core_V3F)
	
#elif (Run_Core == Run_Core_V5F)

	Hardware();

#endif

	while(1)
	{
		printf("V5F running...\r\n");
		Delay_Ms(1000);
	}
}
